Repository Step3-kakao-tech-campus/Team13_BE, pull requests merged in 2023-10, with the labels that each got.

#12 도메인 엔티티 작성
  src/main/java/com/theocean/fundering/celebrity/domain/Celebrity.java
  src/main/java/com/theocean/fundering/celebrity/domain/constant/CelebGender.java
  src/main/java/com/theocean/fundering/celebrity/domain/constant/CelebType.java
  src/main/java/com/theocean/fundering/follow/domain/Follow.java
  src/main/java/com/theocean/fundering/user/domain/User.java
  src/main/java/com/theocean/fundering/user/domain/constant/UserRole.java
  src/test/java/com/theocean/fundering/hello/HelloTest.java
Labels: Priority: High, Type: Feature, Status: In Progress

#15 도메인 엔티티 작성
  src/main/java/com/theocean/fundering/account/domain/Account.java
  src/main/java/com/theocean/fundering/evidence/domain/Evidence.java
  src/main/java/com/theocean/fundering/update/domain/Update.java
Labels: Priority: High, Type: Feature

#17 4주차 작업 내용
  .github/ISSUE_TEMPLATE/feature-issue-template.md
  .github/feature_issue_template.md
  .github/pull_request_template.md
  .gitignore
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/theocean/fundering/FunderingApplication.java
  src/main/java/com/theocean/fundering/account/domain/Account.java
  src/main/java/com/theocean/fundering/admin/domain/Admin.java
  src/main/java/com/theocean/fundering/celebrity/domain/Celebrity.java
  src/main/java/com/theocean/fundering/celebrity/domain/constant/CelebGender.java
  src/main/java/com/theocean/fundering/celebrity/domain/constant/CelebType.java
  src/main/java/com/theocean/fundering/domain/comment/domain/Comment.java
  src/main/java/com/theocean/fundering/domain/like/domain/Like.java
  src/main/java/com/theocean/fundering/domain/post/domain/Post.java
  src/main/java/com/theocean/fundering/evidence/domain/Evidence.java
  src/main/java/com/theocean/fundering/follow/domain/Follow.java
  src/main/java/com/theocean/fundering/payment/domain/Payment.java
  src/main/java/com/theocean/fundering/update/domain/Update.java
  src/main/java/com/theocean/fundering/user/domain/User.java
  src/main/java/com/theocean/fundering/user/domain/constant/UserRole.java
  src/main/java/com/theocean/fundering/withdrawal/domain/Withdrawal.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/com/theocean/fundering/FunderingApplicationTests.java
Labels: Type: Feature, Status: Done

#18 도메인 디렉토리 구조 수정
  src/main/java/com/theocean/fundering/domain/account/domain/Account.java
  src/main/java/com/theocean/fundering/domain/admin/domain/Admin.java
  src/main/java/com/theocean/fundering/domain/celebrity/domain/Celebrity.java
  src/main/java/com/theocean/fundering/domain/celebrity/domain/constant/CelebGender.java
  src/main/java/com/theocean/fundering/domain/celebrity/domain/constant/CelebType.java
  src/main/java/com/theocean/fundering/domain/evidence/domain/Evidence.java
  src/main/java/com/theocean/fundering/domain/follow/domain/Follow.java
  src/main/java/com/theocean/fundering/domain/like/domain/Like.java
  src/main/java/com/theocean/fundering/domain/payment/domain/Payment.java
  src/main/java/com/theocean/fundering/domain/post/domain/Post.java
  src/main/java/com/theocean/fundering/domain/update/domain/Update.java
  src/main/java/com/theocean/fundering/domain/user/domain/User.java
  src/main/java/com/theocean/fundering/domain/user/domain/constant/UserRole.java
  src/main/java/com/theocean/fundering/domain/withdrawal/domain/Withdrawal.java
Labels: Priority: Low, Type: Refactoring

#26 도메인 엔티티 리팩토링
  build.gradle
  src/main/java/com/theocean/fundering/FunderingApplication.java
  src/main/java/com/theocean/fundering/domain/account/domain/Account.java
  src/main/java/com/theocean/fundering/domain/admin/domain/Admin.java
  src/main/java/com/theocean/fundering/domain/celebrity/domain/Celebrity.java
  src/main/java/com/theocean/fundering/domain/comment/domain/Comment.java
  src/main/java/com/theocean/fundering/domain/evidence/domain/Evidence.java
  src/main/java/com/theocean/fundering/domain/follow/domain/Follow.java
  src/main/java/com/theocean/fundering/domain/global/AuditingFields.java
  src/main/java/com/theocean/fundering/domain/like/domain/Heart.java
  src/main/java/com/theocean/fundering/domain/member/domain/Member.java
  src/main/java/com/theocean/fundering/domain/member/domain/constant/UserRole.java
  src/main/java/com/theocean/fundering/domain/payment/domain/Payment.java
  src/main/java/com/theocean/fundering/domain/post/domain/Post.java
  src/main/java/com/theocean/fundering/domain/update/domain/Update.java
  src/main/java/com/theocean/fundering/domain/withdrawal/domain/Withdrawal.java
  src/main/resources/application-local.yml
Labels: Priority: Low, Status: In Progress, Type: Refactoring, Type: Configuration

#29 로그인 기능 개발 상황 공유
  src/main/java/com/theocean/fundering/domain/admin/domain/Admin.java
  src/main/java/com/theocean/fundering/domain/celebrity/domain/Celebrity.java
  src/main/java/com/theocean/fundering/domain/comment/domain/Comment.java
  src/main/java/com/theocean/fundering/domain/evidence/domain/Evidence.java
  src/main/java/com/theocean/fundering/domain/member/controller/MemberController.java
  src/main/java/com/theocean/fundering/domain/member/domain/Member.java
  src/main/java/com/theocean/fundering/domain/member/domain/constant/UserRole.java
  src/main/java/com/theocean/fundering/domain/member/dto/MemberRequestDTO.java
  src/main/java/com/theocean/fundering/domain/member/repository/MemberRepository.java
  src/main/java/com/theocean/fundering/domain/member/service/LoginService.java
  src/main/java/com/theocean/fundering/domain/member/service/MemberService.java
  src/main/java/com/theocean/fundering/domain/news/domain/News.java
  src/main/java/com/theocean/fundering/domain/payment/domain/Payment.java
  src/main/java/com/theocean/fundering/domain/post/domain/Post.java
  src/main/java/com/theocean/fundering/domain/withdrawal/domain/Withdrawal.java
  src/main/java/com/theocean/fundering/global/config/security/SpringSecurityConfig.java
  src/main/java/com/theocean/fundering/global/config/security/custom/CustomJsonUsernamePasswordAuthenticationFilter.java
  src/main/java/com/theocean/fundering/global/config/security/custom/CustomUserDetails.java
  src/main/java/com/theocean/fundering/global/config/security/handler/LoginFailureHandler.java
  src/main/java/com/theocean/fundering/global/config/security/handler/LoginSuccessHandler.java
  src/main/java/com/theocean/fundering/global/config/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/theocean/fundering/global/config/security/jwt/JwtProvider.java
  src/main/java/com/theocean/fundering/global/errors/GlobalExceptionHandler.java
  src/main/java/com/theocean/fundering/global/errors/GlobalValidationHandler.java
  src/main/java/com/theocean/fundering/global/errors/exception/Exception400.java
  src/main/java/com/theocean/fundering/global/errors/exception/Exception401.java
  src/main/java/com/theocean/fundering/global/errors/exception/Exception403.java
  src/main/java/com/theocean/fundering/global/errors/exception/Exception404.java
  src/main/java/com/theocean/fundering/global/errors/exception/Exception500.java
  src/main/java/com/theocean/fundering/global/utils/ApiUtils.java
  src/main/java/com/theocean/fundering/global/utils/AuditingFields.java
  src/main/java/com/theocean/fundering/global/utils/FilterResponseUtils.java
  src/main/java/com/theocean/fundering/global/utils/PasswordUtil.java
  src/main/resources/application-test.yml
Labels: Priority: High, Type: Feature, Status: In Progress, Type: Configuration

#28 댓글 관련 기능 개발
  src/main/java/com/theocean/fundering/domain/comment/controller/CommentController.java
  src/main/java/com/theocean/fundering/domain/comment/domain/Comment.java
  src/main/java/com/theocean/fundering/domain/comment/dto/CommentRequest.java
  src/main/java/com/theocean/fundering/domain/comment/dto/CommentResponse.java
  src/main/java/com/theocean/fundering/domain/comment/repository/CommentRepository.java
  src/main/java/com/theocean/fundering/domain/comment/service/CommentService.java
  src/main/java/com/theocean/fundering/domain/post/domain/Post.java
Labels: Priority: High, Type: Feature, Status: In Progress

#30 OAuth2 login 기능 개발 상황 공유
  build.gradle
  src/main/java/com/theocean/fundering/domain/comment/controller/CommentController.java
  src/main/java/com/theocean/fundering/domain/comment/domain/Comment.java
  src/main/java/com/theocean/fundering/domain/comment/dto/CommentRequest.java
  src/main/java/com/theocean/fundering/domain/comment/dto/CommentResponse.java
  src/main/java/com/theocean/fundering/domain/comment/repository/CommentRepository.java
  src/main/java/com/theocean/fundering/domain/comment/service/CommentService.java
  src/main/java/com/theocean/fundering/domain/member/controller/MemberController.java
  src/main/java/com/theocean/fundering/domain/member/domain/Member.java
  src/main/java/com/theocean/fundering/domain/post/domain/Post.java
  src/main/java/com/theocean/fundering/global/oauth2/CustomOAuth2User.java
  src/main/java/com/theocean/fundering/global/oauth2/OAuthAttributes.java
  src/main/java/com/theocean/fundering/global/oauth2/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/theocean/fundering/global/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/theocean/fundering/global/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/theocean/fundering/global/oauth2/userInfo/KakaoOAuth2UserInfo.java
  src/main/java/com/theocean/fundering/global/oauth2/userInfo/OAuth2UserInfo.java
  src/main/resources/application-oauth.yml
Labels: Priority: High, Type: Feature, Status: In Progress

#31 댓글 기능 리팩토링
  src/main/java/com/theocean/fundering/domain/comment/controller/CommentController.java
  src/main/java/com/theocean/fundering/domain/comment/domain/Comment.java
  src/main/java/com/theocean/fundering/domain/comment/dto/CommentResponse.java
  src/main/java/com/theocean/fundering/domain/comment/repository/CommentRepository.java
  src/main/java/com/theocean/fundering/domain/comment/service/CommentService.java
  src/main/java/com/theocean/fundering/global/errors/GlobalExceptionHandler.java
  src/main/java/com/theocean/fundering/global/errors/exception/Exception400.java
  src/main/java/com/theocean/fundering/global/errors/exception/Exception401.java
  src/main/java/com/theocean/fundering/global/errors/exception/Exception403.java
  src/main/java/com/theocean/fundering/global/errors/exception/Exception404.java
  src/main/java/com/theocean/fundering/global/errors/exception/Exception500.java
  src/main/java/com/theocean/fundering/global/utils/ApiUtils.java
  src/main/java/com/theocean/fundering/global/utils/AuditingFields.java
Labels: Priority: Medium, Status: Done, Type: Refactoring

#33 게시물 관련 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/theocean/fundering/domain/account/domain/Account.java
  src/main/java/com/theocean/fundering/domain/admin/domain/Admin.java
  src/main/java/com/theocean/fundering/domain/celebrity/domain/Celebrity.java
  src/main/java/com/theocean/fundering/domain/evidence/domain/Evidence.java
  src/main/java/com/theocean/fundering/domain/member/domain/Member.java
  src/main/java/com/theocean/fundering/domain/news/domain/News.java
  src/main/java/com/theocean/fundering/domain/payment/domain/Payment.java
  src/main/java/com/theocean/fundering/domain/post/controller/PostController.java
  src/main/java/com/theocean/fundering/domain/post/domain/Post.java
  src/main/java/com/theocean/fundering/domain/post/dto/PostRequest.java
  src/main/java/com/theocean/fundering/domain/post/dto/PostResponse.java
  src/main/java/com/theocean/fundering/domain/post/repository/PostQuerydslRepository.java
  src/main/java/com/theocean/fundering/domain/post/repository/PostQuerydslRepositoryImpl.java
  src/main/java/com/theocean/fundering/domain/post/repository/PostRepository.java
  src/main/java/com/theocean/fundering/domain/post/service/PostService.java
  src/main/java/com/theocean/fundering/domain/withdrawal/domain/Withdrawal.java
  src/main/java/com/theocean/fundering/global/utils/ApiUtils.java
  src/test/java/com/theocean/fundering/post/PostTest.java
Labels: Priority: High, Type: Feature

#34 로그인 기능 구현
  build.gradle
  src/main/java/com/theocean/fundering/domain/member/controller/MemberController.java
  src/main/java/com/theocean/fundering/domain/member/domain/Member.java
  src/main/java/com/theocean/fundering/domain/member/domain/constant/UserRole.java
  src/main/java/com/theocean/fundering/domain/member/dto/MemberRequestDTO.java
  src/main/java/com/theocean/fundering/domain/member/repository/MemberRepository.java
  src/main/java/com/theocean/fundering/domain/member/service/MemberService.java
  src/main/java/com/theocean/fundering/global/config/security/SpringSecurityConfig.java
  src/main/java/com/theocean/fundering/global/errors/GlobalExceptionHandler.java
  src/main/java/com/theocean/fundering/global/errors/GlobalValidationHandler.java
  src/main/java/com/theocean/fundering/global/errors/exception/Exception400.java
  src/main/java/com/theocean/fundering/global/errors/exception/Exception401.java
  src/main/java/com/theocean/fundering/global/errors/exception/Exception403.java
  src/main/java/com/theocean/fundering/global/errors/exception/Exception404.java
  src/main/java/com/theocean/fundering/global/errors/exception/Exception500.java
  src/main/java/com/theocean/fundering/global/jwt/JwtProvider.java
  src/main/java/com/theocean/fundering/global/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/theocean/fundering/global/jwt/handler/LoginFailureHandler.java
  src/main/java/com/theocean/fundering/global/jwt/handler/LoginSuccessHandler.java
  src/main/java/com/theocean/fundering/global/jwt/service/LoginService.java
  src/main/java/com/theocean/fundering/global/jwt/userInfo/CustomJsonUsernamePasswordAuthenticationFilter.java
  src/main/java/com/theocean/fundering/global/jwt/userInfo/CustomUserDetails.java
  src/main/java/com/theocean/fundering/global/oauth2/CustomOAuth2User.java
  src/main/java/com/theocean/fundering/global/oauth2/OAuthAttributes.java
  src/main/java/com/theocean/fundering/global/oauth2/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/theocean/fundering/global/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/theocean/fundering/global/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/theocean/fundering/global/oauth2/userInfo/KakaoOAuth2UserInfo.java
  src/main/java/com/theocean/fundering/global/oauth2/userInfo/OAuth2UserInfo.java
  src/main/java/com/theocean/fundering/global/utils/ApiUtils.java
  src/main/java/com/theocean/fundering/global/utils/FilterResponseUtils.java
  src/main/java/com/theocean/fundering/global/utils/PasswordUtil.java
  src/main/resources/application-local.yml
  src/main/resources/application-oauth.yml
  src/main/resources/application-test.yml
  src/test/java/com/theocean/fundering/domain/member/MemberControllerTest.java
Labels: Priority: High, Type: Feature, Status: In Progress, Type: Refactoring, Type: Configuration

#38 PR 머지 이후 오류 수정
  src/main/java/com/theocean/fundering/domain/account/domain/Account.java
  src/main/java/com/theocean/fundering/domain/admin/domain/Admin.java
  src/main/java/com/theocean/fundering/domain/comment/service/CommentService.java
  src/main/java/com/theocean/fundering/domain/post/domain/Post.java
  src/main/java/com/theocean/fundering/domain/post/repository/PostQuerydslRepositoryImpl.java
  src/main/java/com/theocean/fundering/global/config/QuerydslConfig.java
Labels: Type: Bug, Priority: High, Status: Done

#46 댓글 피드백 사항 반영
  src/main/java/com/theocean/fundering/domain/comment/controller/CommentController.java
  src/main/java/com/theocean/fundering/domain/comment/domain/Comment.java
  src/main/java/com/theocean/fundering/domain/comment/dto/CommentRequest.java
  src/main/java/com/theocean/fundering/domain/comment/dto/CommentResponse.java
  src/main/java/com/theocean/fundering/domain/comment/repository/CommentRepository.java
  src/main/java/com/theocean/fundering/domain/comment/repository/CustomCommentRepository.java
  src/main/java/com/theocean/fundering/domain/comment/repository/CustomCommentRepositoryImpl.java
  src/main/java/com/theocean/fundering/domain/comment/service/CommentService.java
  src/main/java/com/theocean/fundering/global/config/security/SpringSecurityConfig.java
  src/main/java/com/theocean/fundering/global/errors/GlobalExceptionHandler.java
  src/main/java/com/theocean/fundering/global/jwt/userInfo/CustomUserDetails.java
  src/test/java/com/theocean/fundering/comment/CommentControllerTest.java
Labels: Type: Performance, Priority: High, Status: In Progress

#47 셀럽 관련 기능 구현, OAuth 구현
  src/main/java/com/theocean/fundering/domain/celebrity/controller/CelebController.java
  src/main/java/com/theocean/fundering/domain/celebrity/domain/Celebrity.java
  src/main/java/com/theocean/fundering/domain/celebrity/domain/constant/CelebGender.java
  src/main/java/com/theocean/fundering/domain/celebrity/domain/constant/CelebType.java
  src/main/java/com/theocean/fundering/domain/celebrity/dto/CelebDetailsResponseDTO.java
  src/main/java/com/theocean/fundering/domain/celebrity/dto/CelebFundingResponseDTO.java
  src/main/java/com/theocean/fundering/domain/celebrity/dto/CelebListResponseDTO.java
  src/main/java/com/theocean/fundering/domain/celebrity/dto/CelebRequestDTO.java
  src/main/java/com/theocean/fundering/domain/celebrity/dto/PageResponse.java
  src/main/java/com/theocean/fundering/domain/celebrity/repository/CelebRepository.java
  src/main/java/com/theocean/fundering/domain/celebrity/repository/CelebRepositoryCustom.java
  src/main/java/com/theocean/fundering/domain/celebrity/repository/CelebRepositoryImpl.java
  src/main/java/com/theocean/fundering/domain/celebrity/service/CelebService.java
  src/main/java/com/theocean/fundering/domain/member/controller/MemberController.java
  src/main/java/com/theocean/fundering/domain/member/dto/EmailRequestDTO.java
  src/main/java/com/theocean/fundering/domain/member/service/MemberService.java
  src/main/java/com/theocean/fundering/global/config/security/SpringSecurityConfig.java
  src/main/java/com/theocean/fundering/global/errors/GlobalExceptionHandler.java
  src/main/java/com/theocean/fundering/global/errors/exception/Exception400.java
  src/main/java/com/theocean/fundering/global/errors/exception/Exception401.java
  src/main/java/com/theocean/fundering/global/errors/exception/Exception403.java
  src/main/java/com/theocean/fundering/global/errors/exception/Exception404.java
  src/main/java/com/theocean/fundering/global/errors/exception/Exception500.java
  src/main/java/com/theocean/fundering/global/oauth2/OAuthAttributes.java
  src/main/java/com/theocean/fundering/global/oauth2/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/theocean/fundering/global/oauth2/handler/OAuth2LoginSuccessHandler.java
  src/main/java/com/theocean/fundering/global/oauth2/service/CustomOAuth2UserService.java
  src/main/java/com/theocean/fundering/global/oauth2/userInfo/KakaoOAuth2UserInfo.java
  src/main/java/com/theocean/fundering/global/oauth2/userInfo/OAuth2UserInfo.java
  src/main/java/com/theocean/fundering/global/utils/ApiUtils.java
  src/main/resources/application-oauth.yml
  src/main/resources/application.yml
Labels: Type: Bug, Priority: High, Type: Feature, Status: In Progress, Type: Refactoring

#49 펀딩 업데이트 기능 개발
  src/main/java/com/theocean/fundering/domain/news/controller/NewsController.java
  src/main/java/com/theocean/fundering/domain/news/domain/News.java
  src/main/java/com/theocean/fundering/domain/news/dto/NewsRequest.java
  src/main/java/com/theocean/fundering/domain/news/dto/NewsResponse.java
  src/main/java/com/theocean/fundering/domain/news/repository/CustomNewsRepository.java
  src/main/java/com/theocean/fundering/domain/news/repository/CustomNewsRepositoryImpl.java
  src/main/java/com/theocean/fundering/domain/news/repository/NewsRepository.java
  src/main/java/com/theocean/fundering/domain/news/service/NewsService.java
Labels: Priority: High, Type: Feature, Status: In Progress

#56 AWS S3 업로드 기능 추가
  build.gradle
  src/main/java/com/theocean/fundering/domain/celebrity/repository/CelebRepository.java
  src/main/java/com/theocean/fundering/domain/member/repository/MemberRepository.java
  src/main/java/com/theocean/fundering/domain/post/controller/PostController.java
  src/main/java/com/theocean/fundering/domain/post/domain/Post.java
  src/main/java/com/theocean/fundering/domain/post/dto/PostResponse.java
  src/main/java/com/theocean/fundering/domain/post/repository/PostQuerydslRepository.java
  src/main/java/com/theocean/fundering/domain/post/repository/PostQuerydslRepositoryImpl.java
  src/main/java/com/theocean/fundering/domain/post/repository/PostRepository.java
  src/main/java/com/theocean/fundering/domain/post/service/PostService.java
  src/main/java/com/theocean/fundering/global/config/security/SpringSecurityConfig.java
  src/main/java/com/theocean/fundering/global/utils/AWSS3Uploader.java
  src/main/java/com/theocean/fundering/global/utils/HTMLUtils.java
  src/main/resources/application-local.yml
Labels: Priority: High, Type: Feature

#58 간단한 게시글, 댓글 리팩토링
  src/main/java/com/theocean/fundering/domain/comment/controller/CommentController.java
  src/main/java/com/theocean/fundering/domain/comment/domain/Comment.java
  src/main/java/com/theocean/fundering/domain/comment/dto/CommentRequest.java
  src/main/java/com/theocean/fundering/domain/comment/dto/CommentResponse.java
  src/main/java/com/theocean/fundering/domain/comment/repository/CommentRepository.java
  src/main/java/com/theocean/fundering/domain/comment/repository/CustomCommentRepository.java
  src/main/java/com/theocean/fundering/domain/comment/repository/CustomCommentRepositoryImpl.java
  src/main/java/com/theocean/fundering/domain/comment/service/CommentService.java
  src/main/java/com/theocean/fundering/domain/news/controller/NewsController.java
  src/main/java/com/theocean/fundering/domain/news/domain/News.java
  src/main/java/com/theocean/fundering/domain/news/dto/NewsRequest.java
  src/main/java/com/theocean/fundering/domain/news/dto/NewsResponse.java
  src/main/java/com/theocean/fundering/domain/news/repository/CustomNewsRepository.java
  src/main/java/com/theocean/fundering/domain/news/repository/CustomNewsRepositoryImpl.java
  src/main/java/com/theocean/fundering/domain/news/repository/NewsRepository.java
  src/main/java/com/theocean/fundering/domain/news/service/NewsService.java
  src/main/java/com/theocean/fundering/domain/post/controller/PostController.java
  src/main/java/com/theocean/fundering/domain/post/domain/Post.java
  src/main/java/com/theocean/fundering/global/errors/GlobalExceptionHandler.java
  src/test/java/com/theocean/fundering/comment/CommentControllerTest.java
Labels: Priority: Low, Type: Refactoring

#61 셀럽 관련 기능 리팩토링
  src/main/java/com/theocean/fundering/domain/celebrity/controller/CelebController.java
  src/main/java/com/theocean/fundering/domain/celebrity/domain/constant/CelebGender.java
  src/main/java/com/theocean/fundering/domain/celebrity/domain/constant/CelebType.java
  src/main/java/com/theocean/fundering/domain/celebrity/dto/CelebDetailsResponseDTO.java
  src/main/java/com/theocean/fundering/domain/celebrity/dto/CelebRequestDTO.java
  src/main/java/com/theocean/fundering/domain/celebrity/repository/CelebRepositoryImpl.java
  src/main/java/com/theocean/fundering/domain/celebrity/service/CelebService.java
Labels: Priority: Medium, Status: Todo, Type: Refactoring

#62 AWS SDK 2.x로 적용
  build.gradle
  src/main/java/com/theocean/fundering/domain/post/controller/PostController.java
  src/main/java/com/theocean/fundering/domain/post/service/PostService.java
  src/main/java/com/theocean/fundering/global/config/AWSS3Config.java
  src/main/java/com/theocean/fundering/global/utils/AWSS3Uploader.java
  src/main/resources/application-local.yml
Labels: Type: Performance, Priority: Medium

#60 댓글 구조 수정
  src/main/java/com/theocean/fundering/domain/comment/controller/CommentController.java
  src/main/java/com/theocean/fundering/domain/comment/domain/Comment.java
  src/main/java/com/theocean/fundering/domain/comment/dto/CommentRequest.java
  src/main/java/com/theocean/fundering/domain/comment/dto/CommentResponse.java
  src/main/java/com/theocean/fundering/domain/comment/repository/CommentRepository.java
  src/main/java/com/theocean/fundering/domain/comment/repository/CustomCommentRepository.java
  src/main/java/com/theocean/fundering/domain/comment/repository/CustomCommentRepositoryImpl.java
  src/main/java/com/theocean/fundering/domain/comment/service/CommentService.java
Labels: Priority: High, Status: Done, Type: Refactoring

#65 게시물 정렬 기능 추가 및 Dockerfile 추가
  Dockerfile
  src/main/java/com/theocean/fundering/domain/post/controller/PostController.java
  src/main/java/com/theocean/fundering/domain/post/domain/Post.java
  src/main/java/com/theocean/fundering/domain/post/repository/PostQuerydslRepository.java
  src/main/java/com/theocean/fundering/domain/post/repository/PostQuerydslRepositoryImpl.java
  src/main/java/com/theocean/fundering/domain/post/service/PostService.java
  src/main/resources/application-prod.yml
Labels: Priority: Medium, Type: Feature

#68 Post Controller, Service, Repository 리팩토링 및 정렬 기능 수정
  src/main/java/com/theocean/fundering/domain/account/domain/Account.java
  src/main/java/com/theocean/fundering/domain/post/controller/PostController.java
  src/main/java/com/theocean/fundering/domain/post/dto/PostResponse.java
  src/main/java/com/theocean/fundering/domain/post/repository/PostQuerydslRepository.java
  src/main/java/com/theocean/fundering/domain/post/repository/PostQuerydslRepositoryImpl.java
  src/main/java/com/theocean/fundering/domain/post/service/PostService.java
Labels: Type: Performance, Priority: Medium, Status: Done, Type: Refactoring

#69 댓글관련 프론트엔드 피드백 반영
  build.gradle
  src/main/java/com/theocean/fundering/domain/comment/controller/CommentController.java
  src/main/java/com/theocean/fundering/domain/comment/domain/Comment.java
  src/main/java/com/theocean/fundering/domain/comment/dto/CommentRequest.java
  src/main/java/com/theocean/fundering/domain/comment/dto/CommentResponse.java
  src/main/java/com/theocean/fundering/domain/comment/repository/CommentRepository.java
  src/main/java/com/theocean/fundering/domain/comment/repository/CustomCommentRepository.java
  src/main/java/com/theocean/fundering/domain/comment/repository/CustomCommentRepositoryImpl.java
  src/main/java/com/theocean/fundering/domain/comment/service/CommentService.java
  src/main/java/com/theocean/fundering/domain/comment/service/CommentValidator.java
  src/main/java/com/theocean/fundering/global/config/CacheConfig.java
Labels: Priority: High, Status: In Progress, Type: Refactoring

#73 서비스 책임 분리
  src/main/java/com/theocean/fundering/domain/comment/controller/CommentController.java
  src/main/java/com/theocean/fundering/domain/comment/service/CommentService.java
  src/main/java/com/theocean/fundering/domain/comment/service/CommentValidator.java
  src/main/java/com/theocean/fundering/domain/comment/service/CreateCommentService.java
  src/main/java/com/theocean/fundering/domain/comment/service/DeleteCommentService.java
  src/main/java/com/theocean/fundering/domain/comment/service/ReadCommentService.java
  src/main/java/com/theocean/fundering/domain/news/controller/NewsController.java
  src/main/java/com/theocean/fundering/domain/news/domain/News.java
  src/main/java/com/theocean/fundering/domain/news/service/CreateNewsService.java
  src/main/java/com/theocean/fundering/domain/news/service/NewsService.java
  src/main/java/com/theocean/fundering/domain/news/service/ReadNewsService.java
Labels: Priority: Medium, Status: Done, Type: Refactoring

#75 결제 관련 요소 추가 및 Dockerfile 수정
  Dockerfile
  build.gradle
  src/main/java/com/theocean/fundering/domain/payment/domain/controller/PaymentController.java
  src/main/java/com/theocean/fundering/domain/payment/domain/dto/PaymentRequest.java
  src/main/java/com/theocean/fundering/domain/payment/domain/repository/PaymentRepository.java
  src/main/java/com/theocean/fundering/domain/payment/domain/service/PaymentService.java
  src/main/java/com/theocean/fundering/domain/post/controller/PostController.java
  src/main/java/com/theocean/fundering/domain/post/domain/Post.java
  src/main/java/com/theocean/fundering/domain/post/dto/PostRequest.java
  src/main/java/com/theocean/fundering/domain/post/dto/PostResponse.java
  src/main/java/com/theocean/fundering/domain/post/service/PostService.java
  src/main/java/com/theocean/fundering/global/config/PaymentConfig.java
Labels: Priority: High, Type: Feature, Status: In Progress, Type: Configuration, Type: Chore

#74 JWT 로그인 리팩토링 및 셀럽 관련 기능 code inspect 적용
  src/main/java/com/theocean/fundering/domain/celebrity/controller/CelebController.java
  src/main/java/com/theocean/fundering/domain/celebrity/dto/CelebDetailsResponseDTO.java
  src/main/java/com/theocean/fundering/domain/celebrity/service/CelebService.java
  src/main/java/com/theocean/fundering/domain/member/controller/MemberController.java
  src/main/java/com/theocean/fundering/domain/member/domain/constant/UserRole.java
  src/main/java/com/theocean/fundering/domain/member/dto/EmailRequestDTO.java
  src/main/java/com/theocean/fundering/global/config/security/SpringSecurityConfig.java
  src/main/java/com/theocean/fundering/global/jwt/JwtProvider.java
  src/main/java/com/theocean/fundering/global/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/theocean/fundering/global/jwt/handler/LoginFailureHandler.java
  src/main/java/com/theocean/fundering/global/jwt/handler/LoginSuccessHandler.java
  src/main/java/com/theocean/fundering/global/jwt/service/LoginService.java
  src/main/java/com/theocean/fundering/global/jwt/userInfo/CustomJsonUsernamePasswordAuthenticationFilter.java
  src/main/java/com/theocean/fundering/global/jwt/userInfo/CustomUserDetails.java
  src/main/java/com/theocean/fundering/global/oauth2/handler/OAuth2LoginFailureHandler.java
  src/main/java/com/theocean/fundering/global/utils/FilterResponseUtils.java
  src/test/java/com/theocean/fundering/domain/member/MemberControllerTest.java
  src/test/java/com/theocean/fundering/member/MemberControllerTest.java
Labels: Priority: Medium, Type: Test, Type: Refactoring, Type: Style

#76 빌드 오류 수정
  src/main/java/com/theocean/fundering/domain/celebrity/repository/CelebRepositoryImpl.java
  src/main/java/com/theocean/fundering/domain/comment/controller/CommentController.java
  src/test/java/com/theocean/fundering/comment/CommentControllerTest.java
Labels: Type: Bug, Priority: High
