Repository Step3-kakao-tech-campus/Team13_BE, pull requests merged in 2023-09, with the labels that each got.

#3 PR, 이슈 컨벤션 추가
  .github/feature_issue_template.md
  .github/pull_request_template.md
Labels: documentation

#6 docs: README.md 수정
  README.md
Labels: Type: Documentation

#9 init: project initial settings
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/theocean/fundering/FunderingApplication.java
  src/main/java/com/theocean/fundering/hello/Hello.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
  src/main/resources/application.yml
  src/test/java/com/theocean/fundering/FunderingApplicationTests.java
  src/test/java/com/theocean/fundering/hello/HelloTest.java
Labels: Type: Documentation, Priority: High, Status: In Progress, Type: Configuration

#11 init: 도메인형 디렉터리 구조
  src/main/java/com/theocean/fundering/hello/Hello.java
Labels: Priority: Medium, Status: Done, Type: Style
