Repository Step3-kakao-tech-campus/Team13_BE, pull requests merged in 2023-11, with the labels that each got.

#78 CustomUserDetails User Id 추가, 셀럽 검색 기능 추가
  src/main/java/com/theocean/fundering/domain/celebrity/controller/CelebController.java
  src/main/java/com/theocean/fundering/domain/celebrity/repository/CelebRepositoryCustom.java
  src/main/java/com/theocean/fundering/domain/celebrity/repository/CelebRepositoryImpl.java
  src/main/java/com/theocean/fundering/domain/celebrity/service/CelebService.java
  src/main/java/com/theocean/fundering/global/jwt/userInfo/CustomUserDetails.java
  src/test/java/com/theocean/fundering/celebrity/CelebrityControllerTest.java
Labels: Priority: Medium, Type: Wont Fix, Type: Test

#80 Payment 결제 기능 추가 및 Post 성능 개선
  src/main/java/com/theocean/fundering/domain/payment/domain/Payment.java
  src/main/java/com/theocean/fundering/domain/payment/domain/controller/PaymentController.java
  src/main/java/com/theocean/fundering/domain/payment/domain/dto/PaymentRequest.java
  src/main/java/com/theocean/fundering/domain/payment/domain/service/PaymentService.java
  src/main/java/com/theocean/fundering/domain/post/controller/PostController.java
  src/main/java/com/theocean/fundering/domain/post/dto/PostRequest.java
  src/main/java/com/theocean/fundering/domain/post/dto/PostResponse.java
  src/main/java/com/theocean/fundering/domain/post/repository/PostQuerydslRepository.java
  src/main/java/com/theocean/fundering/domain/post/repository/PostQuerydslRepositoryImpl.java
  src/main/java/com/theocean/fundering/domain/post/service/PostService.java
Labels: Type: Performance, Priority: High, Type: Feature, Status: In Progress

#81 payment 패키지 구조 리팩토링 및 프로젝트 빌드 오류 해결
  Dockerfile
  src/main/java/com/theocean/fundering/domain/payment/controller/PaymentController.java
  src/main/java/com/theocean/fundering/domain/payment/dto/PaymentRequest.java
  src/main/java/com/theocean/fundering/domain/payment/repository/PaymentRepository.java
  src/main/java/com/theocean/fundering/domain/payment/service/PaymentService.java
  src/main/java/com/theocean/fundering/domain/post/dto/PostResponse.java
  src/main/java/com/theocean/fundering/domain/post/service/PostService.java
Labels: Priority: Medium, Status: Done, Type: Refactoring

#82 My 펀딩 목록 조회 구현 및 셀럽 등록 기능 구현 및 CustomUserDetails null 오류 수정
  build.gradle
  src/main/java/com/theocean/fundering/domain/celebrity/controller/CelebController.java
  src/main/java/com/theocean/fundering/domain/celebrity/domain/Celebrity.java
  src/main/java/com/theocean/fundering/domain/celebrity/domain/constant/ApprovalStatus.java
  src/main/java/com/theocean/fundering/domain/celebrity/repository/CelebRepositoryCustom.java
  src/main/java/com/theocean/fundering/domain/celebrity/repository/CelebRepositoryImpl.java
  src/main/java/com/theocean/fundering/domain/celebrity/service/CelebService.java
  src/main/java/com/theocean/fundering/domain/member/controller/MemberController.java
  src/main/java/com/theocean/fundering/domain/member/domain/constant/UserRole.java
  src/main/java/com/theocean/fundering/domain/myfunding/controller/MyFundingController.java
  src/main/java/com/theocean/fundering/domain/myfunding/dto/MyFundingHostResponseDTO.java
  src/main/java/com/theocean/fundering/domain/myfunding/dto/MyFundingSupporterResponseDTO.java
  src/main/java/com/theocean/fundering/domain/myfunding/repository/MyFundingRepository.java
  src/main/java/com/theocean/fundering/domain/myfunding/repository/MyFundingRepositoryImpl.java
  src/main/java/com/theocean/fundering/domain/myfunding/service/MyFundingService.java
  src/main/java/com/theocean/fundering/domain/post/controller/PostController.java
  src/main/java/com/theocean/fundering/domain/post/domain/Post.java
  src/main/java/com/theocean/fundering/domain/post/service/PostService.java
  src/main/java/com/theocean/fundering/global/dto/PageResponse.java
  src/main/java/com/theocean/fundering/global/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/com/theocean/fundering/global/jwt/service/LoginService.java
  src/main/java/com/theocean/fundering/global/oauth2/OAuthAttributes.java
Labels: Type: Bug, Priority: High, Type: Feature, Status: In Progress, Type: Style

#84 출금 기능 구현
  src/main/java/com/theocean/fundering/domain/account/controller/AccountController.java
  src/main/java/com/theocean/fundering/domain/account/domain/Account.java
  src/main/java/com/theocean/fundering/domain/account/dto/BalanceResponse.java
  src/main/java/com/theocean/fundering/domain/account/repository/AccountRepository.java
  src/main/java/com/theocean/fundering/domain/account/service/AccountService.java
  src/main/java/com/theocean/fundering/domain/evidence/controller/EvidenceController.java
  src/main/java/com/theocean/fundering/domain/evidence/domain/Evidence.java
  src/main/java/com/theocean/fundering/domain/evidence/repository/EvidenceRepository.java
  src/main/java/com/theocean/fundering/domain/evidence/service/EvidenceService.java
  src/main/java/com/theocean/fundering/domain/post/dto/PostResponse.java
  src/main/java/com/theocean/fundering/domain/post/repository/PostQuerydslRepositoryImpl.java
  src/main/java/com/theocean/fundering/domain/withdrawal/controller/WithdrawalController.java
  src/main/java/com/theocean/fundering/domain/withdrawal/domain/Withdrawal.java
  src/main/java/com/theocean/fundering/domain/withdrawal/dto/WithdrawalRequest.java
  src/main/java/com/theocean/fundering/domain/withdrawal/dto/WithdrawalResponse.java
  src/main/java/com/theocean/fundering/domain/withdrawal/repository/WithdrawalRepository.java
  src/main/java/com/theocean/fundering/domain/withdrawal/service/WithdrawalService.java
Labels: Priority: High, Type: Feature, Status: In Progress

#86 셀럽 팔로우(구독) 기능 구현 및 추천 셀럽 정보 조회 기능 구현
  src/main/java/com/theocean/fundering/domain/celebrity/controller/CelebController.java
  src/main/java/com/theocean/fundering/domain/celebrity/controller/FollowController.java
  src/main/java/com/theocean/fundering/domain/celebrity/domain/Celebrity.java
  src/main/java/com/theocean/fundering/domain/celebrity/domain/Follow.java
  src/main/java/com/theocean/fundering/domain/celebrity/dto/CelebsRecommendDTO.java
  src/main/java/com/theocean/fundering/domain/celebrity/repository/CelebRepository.java
  src/main/java/com/theocean/fundering/domain/celebrity/repository/FollowRepository.java
  src/main/java/com/theocean/fundering/domain/celebrity/service/CelebService.java
  src/main/java/com/theocean/fundering/domain/celebrity/service/FollowService.java
  src/main/java/com/theocean/fundering/domain/follow/domain/Follow.java
  src/main/java/com/theocean/fundering/domain/member/domain/Member.java
Labels: Priority: Medium, Type: Feature, Status: In Progress

#88 My 펀딩과 관련된 기능 구현 및 내 정보 관련 기능 구현
  src/main/java/com/theocean/fundering/FunderingApplication.java
  src/main/java/com/theocean/fundering/domain/celebrity/dto/CelebRequestDTO.java
  src/main/java/com/theocean/fundering/domain/celebrity/dto/CelebsRecommendDTO.java
  src/main/java/com/theocean/fundering/domain/celebrity/repository/FollowRepository.java
  src/main/java/com/theocean/fundering/domain/member/controller/MemberController.java
  src/main/java/com/theocean/fundering/domain/member/domain/Member.java
  src/main/java/com/theocean/fundering/domain/member/dto/EmailRequestDTO.java
  src/main/java/com/theocean/fundering/domain/member/dto/MemberSettingRequestDTO.java
  src/main/java/com/theocean/fundering/domain/member/dto/MemberSettingResponseDTO.java
  src/main/java/com/theocean/fundering/domain/member/dto/MemberSignUpRequestDTO.java
  src/main/java/com/theocean/fundering/domain/member/service/MemberService.java
  src/main/java/com/theocean/fundering/domain/myfunding/controller/MyFundingController.java
  src/main/java/com/theocean/fundering/domain/myfunding/dto/MyFundingFollowingCelebsDTO.java
  src/main/java/com/theocean/fundering/domain/myfunding/service/MyFundingService.java
  src/main/java/com/theocean/fundering/global/config/JpaAuditingConfiguration.java
  src/test/java/com/theocean/fundering/celebrity/CelebrityControllerTest.java
  src/test/java/com/theocean/fundering/member/MemberControllerTest.java
Labels: Priority: Medium, Type: Feature, Type: Refactoring, Type: Style

#89 My 펀딩 출금 신청 페이지 구현
  src/main/java/com/theocean/fundering/domain/myfunding/controller/MyFundingController.java
  src/main/java/com/theocean/fundering/domain/myfunding/dto/MyFundingManagerResponseDTO.java
  src/main/java/com/theocean/fundering/domain/myfunding/repository/MyFundingRepository.java
  src/main/java/com/theocean/fundering/domain/myfunding/repository/MyFundingRepositoryImpl.java
  src/main/java/com/theocean/fundering/domain/myfunding/service/MyFundingService.java
Labels: Priority: High, Type: Feature, Status: In Progress

#91 댓글, 출금 리팩토링
  src/main/java/com/theocean/fundering/domain/celebrity/repository/CelebRepository.java
  src/main/java/com/theocean/fundering/domain/comment/controller/CommentController.java
  src/main/java/com/theocean/fundering/domain/comment/service/ReadCommentService.java
  src/main/java/com/theocean/fundering/domain/evidence/controller/EvidenceController.java
  src/main/java/com/theocean/fundering/domain/evidence/domain/Evidence.java
  src/main/java/com/theocean/fundering/domain/evidence/service/EvidenceService.java
  src/main/java/com/theocean/fundering/domain/news/controller/NewsController.java
  src/main/java/com/theocean/fundering/domain/post/controller/PostController.java
  src/main/java/com/theocean/fundering/domain/post/domain/Post.java
  src/main/java/com/theocean/fundering/domain/post/dto/PostRequest.java
  src/main/java/com/theocean/fundering/domain/post/service/PostService.java
  src/main/java/com/theocean/fundering/domain/withdrawal/controller/WithdrawalController.java
  src/main/java/com/theocean/fundering/domain/withdrawal/domain/Withdrawal.java
  src/main/java/com/theocean/fundering/domain/withdrawal/repository/WithdrawalRepository.java
Labels: Priority: Medium, Status: In Progress, Type: Refactoring

#90 팔로우 관련 기능 추가 및 이미지 업로드 기능 추가
  src/main/java/com/theocean/fundering/domain/account/controller/AccountController.java
  src/main/java/com/theocean/fundering/domain/admin/domain/Admin.java
  src/main/java/com/theocean/fundering/domain/celebrity/controller/CelebController.java
  src/main/java/com/theocean/fundering/domain/celebrity/controller/FollowController.java
  src/main/java/com/theocean/fundering/domain/celebrity/domain/Celebrity.java
  src/main/java/com/theocean/fundering/domain/celebrity/domain/Follow.java
  src/main/java/com/theocean/fundering/domain/celebrity/domain/constant/CelebCategory.java
  src/main/java/com/theocean/fundering/domain/celebrity/dto/CelebDetailsResponseDTO.java
  src/main/java/com/theocean/fundering/domain/celebrity/dto/CelebListResponseDTO.java
  src/main/java/com/theocean/fundering/domain/celebrity/dto/CelebRequestDTO.java
  src/main/java/com/theocean/fundering/domain/celebrity/dto/CelebsRecommendResponseDTO.java
  src/main/java/com/theocean/fundering/domain/celebrity/repository/CelebRepository.java
  src/main/java/com/theocean/fundering/domain/celebrity/repository/CelebRepositoryCustom.java
  src/main/java/com/theocean/fundering/domain/celebrity/repository/CelebRepositoryImpl.java
  src/main/java/com/theocean/fundering/domain/celebrity/repository/FollowRepository.java
  src/main/java/com/theocean/fundering/domain/celebrity/service/CelebService.java
  src/main/java/com/theocean/fundering/domain/celebrity/service/FollowService.java
  src/main/java/com/theocean/fundering/domain/comment/controller/CommentController.java
  src/main/java/com/theocean/fundering/domain/evidence/controller/EvidenceController.java
  src/main/java/com/theocean/fundering/domain/follow/domain/Follow.java
  src/main/java/com/theocean/fundering/domain/member/controller/MemberController.java
  src/main/java/com/theocean/fundering/domain/member/controller/MyFundingController.java
  src/main/java/com/theocean/fundering/domain/member/domain/Admin.java
  src/main/java/com/theocean/fundering/domain/member/domain/Member.java
  src/main/java/com/theocean/fundering/domain/member/dto/MemberSettingRequestDTO.java
  src/main/java/com/theocean/fundering/domain/member/dto/MemberSettingResponseDTO.java
  src/main/java/com/theocean/fundering/domain/member/dto/MemberSignUpRequestDTO.java
  src/main/java/com/theocean/fundering/domain/member/dto/MyFundingFollowingCelebsDTO.java
  src/main/java/com/theocean/fundering/domain/member/dto/MyFundingHostResponseDTO.java
  src/main/java/com/theocean/fundering/domain/member/dto/MyFundingSupporterResponseDTO.java
  src/main/java/com/theocean/fundering/domain/member/dto/MyFundingWithdrawalResponseDTO.java
  src/main/java/com/theocean/fundering/domain/member/repository/AdminRepository.java
  src/main/java/com/theocean/fundering/domain/member/repository/MyFundingRepository.java
  src/main/java/com/theocean/fundering/domain/member/repository/MyFundingRepositoryImpl.java
  src/main/java/com/theocean/fundering/domain/member/service/MemberService.java
  src/main/java/com/theocean/fundering/domain/member/service/MyFundingService.java
  src/main/java/com/theocean/fundering/domain/myfunding/controller/MyFundingController.java
  src/main/java/com/theocean/fundering/domain/myfunding/repository/MyFundingRepository.java
  src/main/java/com/theocean/fundering/domain/myfunding/repository/MyFundingRepositoryImpl.java
  src/main/java/com/theocean/fundering/domain/news/controller/NewsController.java
  src/main/java/com/theocean/fundering/domain/post/controller/PostController.java
  src/main/java/com/theocean/fundering/domain/post/repository/PostQuerydslRepositoryImpl.java
  src/main/java/com/theocean/fundering/domain/post/repository/PostRepository.java
  src/main/java/com/theocean/fundering/domain/withdrawal/controller/WithdrawalController.java
  src/main/java/com/theocean/fundering/global/errors/exception/Exception400.java
  src/main/java/com/theocean/fundering/global/errors/exception/Exception401.java
  src/main/java/com/theocean/fundering/global/errors/exception/Exception403.java
  src/main/java/com/theocean/fundering/global/errors/exception/Exception404.java
  src/main/java/com/theocean/fundering/global/errors/exception/Exception500.java
  src/main/java/com/theocean/fundering/global/jwt/handler/LoginFailureHandler.java
  src/main/java/com/theocean/fundering/global/oauth2/handler/OAuth2LoginFailureHandler.java
  src/test/java/com/theocean/fundering/celebrity/CelebrityControllerTest.java
Labels: Priority: Medium, Type: Feature, Type: Style

#95 출금 조회 응답 필드명 변경
  src/main/java/com/theocean/fundering/domain/account/controller/AccountController.java
  src/main/java/com/theocean/fundering/domain/comment/controller/CommentController.java
  src/main/java/com/theocean/fundering/domain/comment/repository/CommentRepository.java
  src/main/java/com/theocean/fundering/domain/comment/service/CommentValidator.java
  src/main/java/com/theocean/fundering/domain/evidence/controller/EvidenceController.java
  src/main/java/com/theocean/fundering/domain/evidence/service/EvidenceService.java
  src/main/java/com/theocean/fundering/domain/news/controller/NewsController.java
  src/main/java/com/theocean/fundering/domain/withdrawal/controller/WithdrawalController.java
  src/main/java/com/theocean/fundering/domain/withdrawal/domain/Withdrawal.java
  src/main/java/com/theocean/fundering/domain/withdrawal/dto/WithdrawalResponse.java
  src/main/java/com/theocean/fundering/domain/withdrawal/service/WithdrawalService.java
Labels: Priority: Medium, Status: Done, Type: Refactoring

#99 Post 컨트롤러 SWAGGER UI 적용 및 AWS S3 Credential 환경 변수 적용
  src/main/java/com/theocean/fundering/domain/heart/controller/HeartController.java
  src/main/java/com/theocean/fundering/domain/heart/domain/Heart.java
  src/main/java/com/theocean/fundering/domain/heart/repository/HeartRepository.java
  src/main/java/com/theocean/fundering/domain/heart/service/HeartService.java
  src/main/java/com/theocean/fundering/domain/payment/controller/PaymentController.java
  src/main/java/com/theocean/fundering/domain/payment/dto/PaymentRequest.java
  src/main/java/com/theocean/fundering/domain/payment/service/PaymentService.java
  src/main/java/com/theocean/fundering/domain/post/controller/PostController.java
  src/main/java/com/theocean/fundering/domain/post/domain/Post.java
  src/main/java/com/theocean/fundering/domain/post/dto/PostRequest.java
  src/main/java/com/theocean/fundering/domain/post/dto/PostResponse.java
  src/main/java/com/theocean/fundering/domain/post/repository/PostQuerydslRepositoryImpl.java
  src/main/java/com/theocean/fundering/domain/post/service/PostService.java
  src/main/java/com/theocean/fundering/global/config/AWSS3Config.java
  src/main/java/com/theocean/fundering/global/utils/ImageUploadController.java
  src/main/resources/application-cloud.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
  src/test/java/com/theocean/fundering/post/PostTest.java
Labels: Priority: High, Type: Refactoring, Type: Chore

#98 공동 관리자 펀딩 출금 승인, 거부 기능 구현
  build.gradle
  src/main/java/com/theocean/fundering/domain/celebrity/domain/Celebrity.java
  src/main/java/com/theocean/fundering/domain/celebrity/repository/CelebRepositoryImpl.java
  src/main/java/com/theocean/fundering/domain/member/controller/MyFundingController.java
  src/main/java/com/theocean/fundering/domain/member/dto/MyFundingWithdrawalResponseDTO.java
  src/main/java/com/theocean/fundering/domain/member/repository/AdminRepository.java
  src/main/java/com/theocean/fundering/domain/member/repository/MyFundingRepository.java
  src/main/java/com/theocean/fundering/domain/member/repository/MyFundingRepositoryImpl.java
  src/main/java/com/theocean/fundering/domain/member/service/MyFundingService.java
  src/main/java/com/theocean/fundering/domain/withdrawal/domain/Withdrawal.java
  src/main/java/com/theocean/fundering/domain/withdrawal/repository/WithdrawalRepository.java
  src/main/java/com/theocean/fundering/global/utils/ApprovalStatus.java
Labels: Priority: High, Type: Feature

#101 날짜 데이터 LocalDateTime으로 리턴
  src/main/java/com/theocean/fundering/domain/comment/dto/CommentResponse.java
  src/main/java/com/theocean/fundering/domain/news/controller/NewsController.java
  src/main/java/com/theocean/fundering/domain/news/dto/NewsResponse.java
  src/main/java/com/theocean/fundering/domain/withdrawal/domain/Withdrawal.java
  src/main/java/com/theocean/fundering/domain/withdrawal/dto/WithdrawalResponse.java
  src/main/java/com/theocean/fundering/domain/withdrawal/service/WithdrawalService.java
Labels: Priority: Medium, Status: Done, Type: Refactoring

#103 fix: 빌드 오류 수정
  src/main/java/com/theocean/fundering/domain/heart/controller/HeartController.java
  src/main/resources/application.yml
Labels: Type: Bug, Priority: High

#107 이미지 업로드 api swagger 설정
  src/main/java/com/theocean/fundering/global/config/SwaggerConfig.java
  src/main/java/com/theocean/fundering/global/utils/ImageUploadController.java
Labels: Priority: Medium, Status: Done, Type: Configuration

#108 AWS S3 API PROXY 설정 추가
  build.gradle
  src/main/java/com/theocean/fundering/global/config/AWSS3Config.java
  src/main/java/com/theocean/fundering/global/utils/AWSS3Uploader.java
Labels: Priority: High, Status: Done, Type: Configuration

#109 테이블 필드명 명시화
  src/main/java/com/theocean/fundering/domain/account/domain/Account.java
  src/main/java/com/theocean/fundering/domain/celebrity/domain/Celebrity.java
  src/main/java/com/theocean/fundering/domain/celebrity/repository/CelebRepository.java
  src/main/java/com/theocean/fundering/domain/comment/domain/Comment.java
  src/main/java/com/theocean/fundering/domain/evidence/domain/Evidence.java
  src/main/java/com/theocean/fundering/domain/heart/domain/Heart.java
  src/main/java/com/theocean/fundering/domain/heart/service/HeartService.java
  src/main/java/com/theocean/fundering/domain/member/domain/Member.java
  src/main/java/com/theocean/fundering/domain/member/dto/MyFundingWithdrawalResponseDTO.java
  src/main/java/com/theocean/fundering/domain/member/repository/MyFundingRepositoryImpl.java
  src/main/java/com/theocean/fundering/domain/member/service/MyFundingService.java
  src/main/java/com/theocean/fundering/domain/news/domain/News.java
  src/main/java/com/theocean/fundering/domain/payment/domain/Payment.java
  src/main/java/com/theocean/fundering/domain/post/domain/Post.java
  src/main/java/com/theocean/fundering/domain/withdrawal/domain/Withdrawal.java
  src/main/java/com/theocean/fundering/domain/withdrawal/dto/WithdrawalResponse.java
  src/main/java/com/theocean/fundering/global/utils/AuditingFields.java
Labels: Priority: High, Status: Done, Type: Refactoring

#111 모든 컨트롤러 /api 추가
  src/main/java/com/theocean/fundering/domain/account/controller/AccountController.java
  src/main/java/com/theocean/fundering/domain/celebrity/controller/CelebController.java
  src/main/java/com/theocean/fundering/domain/celebrity/controller/FollowController.java
  src/main/java/com/theocean/fundering/domain/comment/controller/CommentController.java
  src/main/java/com/theocean/fundering/domain/evidence/controller/EvidenceController.java
  src/main/java/com/theocean/fundering/domain/heart/controller/HeartController.java
  src/main/java/com/theocean/fundering/domain/member/controller/MemberController.java
  src/main/java/com/theocean/fundering/domain/member/controller/MyFundingController.java
  src/main/java/com/theocean/fundering/domain/news/controller/NewsController.java
  src/main/java/com/theocean/fundering/domain/payment/controller/PaymentController.java
  src/main/java/com/theocean/fundering/domain/post/controller/PostController.java
  src/main/java/com/theocean/fundering/domain/withdrawal/controller/WithdrawalController.java
Labels: Priority: High, Type: Feature

#112 Swagger 세부 설정 변경
  src/main/java/com/theocean/fundering/domain/account/controller/AccountController.java
  src/main/java/com/theocean/fundering/domain/evidence/controller/EvidenceController.java
  src/main/java/com/theocean/fundering/domain/news/controller/NewsController.java
  src/main/java/com/theocean/fundering/domain/news/dto/NewsRequest.java
  src/main/java/com/theocean/fundering/domain/news/service/CreateNewsService.java
  src/main/resources/application-local.yml
Labels: Type: Documentation, Priority: Medium, Status: In Progress

#115 swagger test 시 application/octet-stream not supported 에러 해결 용 컴포넌트 추가
  src/main/java/com/theocean/fundering/domain/post/service/PostService.java
  src/main/java/com/theocean/fundering/global/utils/MultipartJackson2HttpMessageConverter.java
Labels: Priority: High, Type: Feature, Status: Done

#117 출금 승인 로직 추가
  src/main/java/com/theocean/fundering/InitialDataInjection.java
  src/main/java/com/theocean/fundering/domain/account/domain/Account.java
  src/main/java/com/theocean/fundering/domain/evidence/controller/EvidenceController.java
  src/main/java/com/theocean/fundering/domain/member/service/MyFundingService.java
  src/main/java/com/theocean/fundering/domain/withdrawal/domain/Withdrawal.java
Labels: Priority: High, Type: Feature, Status: Done

#123 Readme.md 수정
  README.md
Labels: Type: Documentation, Priority: High

#124 유스케이스 링크로 변경
  README.md
Labels: Type: Documentation, Priority: Low

#125 찜하기 관련 요소 이름 수정 및 post 무한 스크롤 로직 수정
  src/main/java/com/theocean/fundering/domain/post/controller/HeartController.java
  src/main/java/com/theocean/fundering/domain/post/controller/PostController.java
  src/main/java/com/theocean/fundering/domain/post/domain/Post.java
  src/main/java/com/theocean/fundering/domain/post/repository/HeartRepository.java
  src/main/java/com/theocean/fundering/domain/post/repository/PostQuerydslRepository.java
  src/main/java/com/theocean/fundering/domain/post/repository/PostQuerydslRepositoryImpl.java
  src/main/java/com/theocean/fundering/domain/post/service/HeartService.java
  src/main/java/com/theocean/fundering/domain/post/service/PostService.java
  src/main/java/com/theocean/fundering/global/dto/PageResponse.java
Labels: Priority: Low, Status: Done, Type: Refactoring

#122 셀럽 조회 문제 수정
  src/main/java/com/theocean/fundering/domain/celebrity/controller/CelebController.java
  src/main/java/com/theocean/fundering/domain/celebrity/dto/CelebResponse.java
  src/main/java/com/theocean/fundering/domain/celebrity/repository/CelebRepository.java
  src/main/java/com/theocean/fundering/domain/celebrity/repository/CelebRepositoryCustom.java
  src/main/java/com/theocean/fundering/domain/celebrity/repository/CelebRepositoryImpl.java
  src/main/java/com/theocean/fundering/domain/celebrity/service/CelebService.java
  src/main/java/com/theocean/fundering/domain/member/controller/MyFundingController.java
  src/main/java/com/theocean/fundering/domain/member/repository/MyFundingRepository.java
  src/main/java/com/theocean/fundering/domain/member/repository/MyFundingRepositoryImpl.java
  src/main/java/com/theocean/fundering/domain/member/service/MyFundingService.java
  src/main/java/com/theocean/fundering/domain/post/domain/Post.java
  src/main/java/com/theocean/fundering/domain/post/repository/PostRepository.java
  src/main/java/com/theocean/fundering/global/jwt/JwtProvider.java
  src/main/resources/application-local.yml
Labels: Priority: High, Type: Feature

#127 fix: 설정 파일로 인한 빌드 오류 수정
  src/main/resources/application-local.yml
Labels: Type: Bug, Priority: High

#126 docs: ERD 작성
  README.md
Labels: Type: Documentation, Priority: Medium

#128 상수 static final로 설정
  src/main/java/com/theocean/fundering/domain/post/service/HeartService.java
  src/main/java/com/theocean/fundering/domain/post/service/PostEventListener.java
  src/main/java/com/theocean/fundering/domain/post/service/PostService.java
Labels: Priority: Medium, Status: Done, Type: Refactoring

#129 셀럽 검색 버그 수정
  src/main/java/com/theocean/fundering/domain/celebrity/controller/CelebController.java
  src/main/java/com/theocean/fundering/domain/celebrity/repository/CelebRepositoryImpl.java
Labels: Priority: High

#130 post 관련 오류 해결 및 리팩토링
  README.md
  src/main/java/com/theocean/fundering/domain/account/service/AccountService.java
  src/main/java/com/theocean/fundering/domain/post/controller/HeartController.java
  src/main/java/com/theocean/fundering/domain/post/controller/PostController.java
  src/main/java/com/theocean/fundering/domain/post/domain/Heart.java
  src/main/java/com/theocean/fundering/domain/post/domain/Post.java
  src/main/java/com/theocean/fundering/domain/post/dto/PostRequest.java
  src/main/java/com/theocean/fundering/domain/post/repository/PostQuerydslRepository.java
  src/main/java/com/theocean/fundering/domain/post/repository/PostQuerydslRepositoryImpl.java
  src/main/java/com/theocean/fundering/domain/post/service/HeartService.java
  src/main/java/com/theocean/fundering/domain/post/service/PostEventListener.java
  src/main/java/com/theocean/fundering/domain/post/service/PostService.java
  src/main/java/com/theocean/fundering/domain/post/service/PostStatusChanger.java
  src/main/java/com/theocean/fundering/global/errors/exception/ErrorCode.java
Labels: Priority: High, Status: Done, Type: Refactoring

#131 셀럽 펀딩 조회 DTO 업데이트
  src/main/java/com/theocean/fundering/domain/celebrity/controller/CelebController.java
  src/main/java/com/theocean/fundering/domain/celebrity/dto/CelebRequest.java
  src/main/java/com/theocean/fundering/domain/celebrity/dto/CelebResponse.java
  src/main/java/com/theocean/fundering/domain/celebrity/repository/CelebRepositoryCustom.java
  src/main/java/com/theocean/fundering/domain/celebrity/repository/CelebRepositoryImpl.java
  src/main/java/com/theocean/fundering/domain/celebrity/service/CelebService.java
  src/main/java/com/theocean/fundering/domain/member/dto/MemberRequest.java
  src/main/java/com/theocean/fundering/global/config/security/SpringSecurityConfig.java
Labels: Priority: High, Type: Refactoring
